apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-manager
  template:
    metadata:
      labels:
        app: pod-manager
    spec:
      serviceAccountName: pod-manager-sa
      containers:
        - name: webhook
          image: pod-manager:v1.0.0
          ports:
            - containerPort: 8443
          env:
            - name: CPU_OVERCOMMIT_RATIO
              value: "1.3"
            - name: MEMORY_OVERCOMMIT_RATIO
              value: "1.2"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # 可选：设置目标命名空间
            - name: TARGET_NAMESPACES
              value: "default"
          volumeMounts:
            - name: certs
              mountPath: /etc/webhook/certs
              readOnly: false
      volumes:
        - name: certs
          emptyDir: {}
          # 不再使用预先创建的证书secret，而是在运行时动态生成

---
apiVersion: v1
kind: Service
metadata:
  name: pod-manager
spec:
  selector:
    app: pod-manager
  ports:
    - port: 443
      targetPort: 8443